var SIDE_PANEL_BOARD_WIDTH=200,RIVER_WIDTH=400,FOLIAGE_WIDTH=66,ARROW_KEY_LEFT=37,ARROW_KEY_UP=38,ARROW_KEY_RIGHT=39,ARROW_KEY_DOWN=40,SPACEBAR=32,stage,queue,riverStream,riverStreamMatrix,frog_sequence,frog,insects_sequence,insects=[],leafs=[],score=[],lifes=[],gameRuning=!1,startScreen,gameEnd=!1,frog_data={images:["assets/frog_spritesheet.png"],frames:[[0,0,60,90],[70,0,60,90]],animations:{seating:[0],jumping:[1]}},insects_data={images:["assets/insects_spritesheet.png"],frames:[[0,0,50,50],[50,
0,50,50],[100,0,50,50],[0,50,50,50],[50,50,50,50],[100,50,50,50]],animations:{insect1:[0],insect2:[1],insect3:[2],insect4:[3],insect5:[4],insect6:[5]}};
function preload(){queue=new createjs.LoadQueue;queue.addEventListener("complete",init);queue.loadManifest([{id:"side_panel",src:"assets/grass-vector-side.jpg"},{id:"river",src:"assets/river-stream-vector.jpg"},{id:"foliage",src:"assets/foliage-vector.png"},{id:"leaf",src:"assets/leaf-vector.png"},{id:"frog",src:"assets/frog_spritesheet.png"},{id:"insects",src:"assets/insects_spritesheet.png"}])}
function init(){canvas=document.getElementById("canvas");stage=new createjs.Stage(canvas);buidlingGameBackground();createInsects();addLeafsAndInsects();addFrog();setFrogPosition();buildScoreBoard();buildLifeBoard();buildStartScreen();startGame();window.onkeydown=moveFrog}
function buidlingGameBackground(){var a=new createjs.Bitmap(queue.getResult("side_panel"));stage.addChild(a);a=new createjs.Bitmap(queue.getResult("side_panel"));a.x=SIDE_PANEL_BOARD_WIDTH+RIVER_WIDTH;stage.addChild(a);a=queue.getResult("river");riverStreamMatrix=new createjs.Matrix2D;riverStreamMatrix.translate(0,0);riverStream=new createjs.Shape;riverStream.graphics.beginBitmapFill(a,"repeat",riverStreamMatrix);riverStream.graphics.drawRect(0,0,RIVER_WIDTH,canvas.height);riverStream.x=SIDE_PANEL_BOARD_WIDTH;
stage.addChild(riverStream);a=new createjs.Bitmap(queue.getResult("foliage"));a.regX=FOLIAGE_WIDTH/2;a.x=SIDE_PANEL_BOARD_WIDTH;a.shadow=new createjs.Shadow("rgba(0,0,0,0.8)",0,0,10);stage.addChild(a);a=new createjs.Bitmap(queue.getResult("foliage"));a.regX=FOLIAGE_WIDTH/2;a.x=SIDE_PANEL_BOARD_WIDTH+RIVER_WIDTH;a.shadow=new createjs.Shadow("rgba(0,0,0,0.8)",0,0,10);stage.addChild(a)}
function createInsects(){insects_sequence=new createjs.SpriteSheet(insects_data);for(var a=0;6>a;a++){var b=new createjs.Sprite(insects_sequence);b.regX=25;b.regY=25;b.gotoAndStop(a);insects.push(b)}}
function addLeafsAndInsects(){for(var a=queue.getResult("leaf"),b=0;5>b;b++){var c=new createjs.Container;c.x=SIDE_PANEL_BOARD_WIDTH+100+Math.floor(200*Math.random());c.y=150*b+-100;c.velX=2*Math.random()-1;c.velY=.75;c.rotationStep=1*Math.random()-.5;var d=new createjs.Shape,e=new createjs.Matrix2D;e.translate(-50,-50);d.graphics.beginBitmapFill(a,"no-repeat",e);d.graphics.drawCircle(0,0,50);c.addChild(d);addInsect(c);stage.addChild(c);leafs.push(c)}}
function addFrog(){frog_sequence=new createjs.SpriteSheet(frog_data);frog=new createjs.Sprite(frog_sequence);frog.gotoAndStop("seating");frog.regX=30;frog.regY=45;frog.status="seating";stage.addChild(frog)}function setFrogPosition(){for(var a=0;a<leafs.length;a++){var b=leafs[a];if(200<b.y&&400>b.y){frog.onTheLeaf=a;removeInsect(b);break}}}
function buildStartScreen(){startScreen=new createjs.Container;startScreen.x=stage.canvas.width/2;startScreen.y=stage.canvas.height/2;stage.addChild(startScreen);var a=new createjs.Text("FROGGY","72px Righteous","#11ff11");a.textAlign="center";a.y=-200;startScreen.addChild(a);a=new createjs.Text("Press any key to","24px Righteous","#fff");a.textAlign="center";a.y=-100;startScreen.addChild(a);a=new createjs.Text("Start Game","48px Righteous","#fff");a.textAlign="center";a.y=-40;startScreen.addChild(a);
a=new createjs.Text("Use left and right arrow key to turn left right","24px Righteous","#fff");a.textAlign="center";a.y=50;startScreen.addChild(a);a=new createjs.Text("Spacebar to Jump","24px Righteous","#fff");a.textAlign="center";a.y=80;startScreen.addChild(a)}function moveFrog(a){if(gameRuning||gameEnd)switch(a.keyCode){case ARROW_KEY_LEFT:frog.rotation+=-10;break;case ARROW_KEY_RIGHT:frog.rotation+=10;break;case SPACEBAR:jumpFrog()}else gameRuning=!0,stage.removeChild(startScreen)}
function jumpFrog(){var a=toRadians(frog.rotation),b=new createjs.Point(frog.x,frog.y),c=new createjs.Point,d=new createjs.Point;d.x=200*Math.sin(a);d.y=200*Math.cos(a);c.x=b.x+d.x;c.y=b.y-d.y;"seating"==frog.status&&(frog.status="jumping",frog.gotoAndStop("jumping"),createjs.Tween.get(frog,{override:!0,onChange:frogJumpProgress}).to({x:c.x,y:c.y},300).call(frogJumpComplete))}
function frogJumpProgress(){for(var a,b=0;b<leafs.length;b++)if(frog.onTheLeaf!=b){var c=leafs[b];a=c.globalToLocal(frog.x,frog.y);if(a=c.hitTest(a.x,a.y)){frog.onTheLeaf=b;b=c.getChildAt(1).currentFrame;score[b].text+=1;removeInsect(c);frog.status="seating";frog.gotoAndStop("seating");createjs.Tween.get(frog,{override:!0});updateScore();break}}}
function frogJumpComplete(){frog.visible=!1;frog.status="seating";frog.gotoAndStop("seating");setTimeout(function(){frog.visible=!0;setFrogPosition()},3E3);removeOneLife()}function toRadians(a){return Math.PI/180*a}function addInsect(a){var b=insects[Math.floor(5*Math.random())].clone();a.addChild(b)}function removeInsect(a){a.removeChildAt(1)}function startGame(){createjs.Ticker.setFPS(60);createjs.Ticker.addEventListener("tick",function(a){gameRuning&&gameLoop();stage.update()})}
function gameLoop(){reverFlow();moveLeafs()}function reverFlow(){riverStreamMatrix.ty+=1;800<=riverStreamMatrix.ty&&(riverStreamMatrix.ty=0)}
function moveLeafs(){for(var a=0;a<leafs.length;a++){var b=leafs[a];b.rotation+=b.rotationStep;b.x+=b.velX;if(275>b.x||525<b.x)b.velX*=-1;b.y+=b.velY;700<b.y&&(b.x=SIDE_PANEL_BOARD_WIDTH+100+Math.floor(200*Math.random()),b.y=-50,b.rotationStep=1*Math.random()-.5,2>b.numChildren&&addInsect(b))}"seating"==frog.status&&(a=leafs[frog.onTheLeaf],frog.x=a.x,frog.y=a.y,frog.rotation+=a.rotationStep,650<frog.y&&(setFrogPosition(),removeOneLife()))}
function buildScoreBoard(){for(var a=0;a<insects.length;a++){var b=insects[a].clone();b.x=SIDE_PANEL_BOARD_WIDTH+RIVER_WIDTH+75;b.y=75*a+100;stage.addChild(b);b=new createjs.Text(0,"35px Righteous","#ff7700");b.textBaseline="middle";b.textAlign="right";b.x=2*SIDE_PANEL_BOARD_WIDTH+RIVER_WIDTH-50;b.y=75*a+100;stage.addChild(b);score.push(b)}}
function buildLifeBoard(){for(var a=0;5>a;a++){var b=frog.clone();b.x=90;b.y=100*a+100;b.shadow=new createjs.Shadow("#fff",0,0,5);stage.addChild(b);lifes.push(b)}}function removeOneLife(){0<lifes.length?stage.removeChild(lifes.pop()):gameRuning&&gameOver()}function gameOver(){gameRuning=!1;gameEnd=!0;var a=new createjs.Text("Game Over","48px Righteous","#fff");a.textBaseline="middle";a.textAlign="center";a.x=stage.canvas.width/2;a.y=stage.canvas.height/2;stage.addChild(a)};